import "./globals.css";
import { ThemeProvider } from "./providers/theme-provider";
import { AuthProvider } from "./backend/context/auth";
import AuthStateChanged from "./backend/layout/authstatechanged";

export const metadata = {
  title: "Jpc",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
           <AuthProvider>
            <AuthStateChanged>
              {children}
            </AuthStateChanged>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
